### ISSUE TITLE
Add CSS template parser

### ISSUE THREAD

**Issue by carry0987** [carry0987/PHP-Template-Engine#1]
Use the following code to define css block
```css
/*[index]*/
.header {
display: block;
}
/*[/index]*/
```
Regex
```regex
/\/\*\[(.+?)\]\*\/(.*?)\/\*\[\/(.+?)\]\*\//is
```
